### ISSUE TITLE
Typo error in : raise_ref_not_found_error

### ISSUE THREAD

**Issue by bbaltagi-dtsl** [LewisDavies/upstream-prod#20]
Macro raise_ref_not_found_error.sql

Replace 
`SCHEMA:   {{ realtion.schema }}`

With 
`SCHEMA:   {{ relation.schema }}`

**Comment by LewisDavies** [comment]
Thanks for catching this. It must have crept in when I refactored the code before the last release. A new minor update will be available soon.
